### ISSUE TITLE
Please support a real dark mode in GNOME

### ISSUE THREAD

**Issue by sudwhiwdh** [freedomofpress/dangerzone#1124]
Currently, the only thing that goes dark is the window decoration with the window title. But not the app content itself. It would be really good for my eyes if there was also a Dangerzone interface in dark mode. And it also looks more consistent in a desktop that as a whole also works in dark mode.

Dangerzone 0.8.1
 Using Fedora Workstation 41

**Comment by apyrgio** [comment]
Hi @sudwhiwdh! Sorry for taking a while to respond, but we were busy with releasing Dangezone 0.9.0.

To your question, Dangerzone should support dark mode actually: https://github.com/freedomofpress/dangerzone/pull/550. If you run `dangerzone` from the CLI, it should report whether dark mode is detected or not. Can you paste the output here?

**Comment by sudwhiwdh** [comment]
@apyrgio I understand that very well. Thank you for working on 0.9.0!

Here is my CLI output:

user@fedora:~$ dangerzone
[DEBUG] Inferred system color scheme as OSColorMode.LIGHT
[DEBUG] Setting up Dangerzone updater
[DEBUG] Consulting updater settings before checking for updates
[DEBUG] Checking platform type
[DEBUG] Running on Linux, disabling updates
[DEBUG] Will not check for updates, based on updater settings

**Comment by sudwhiwdh** [comment]
> Was dark mode working for you in previous Dangerzone versions?

Thanks for checking!
No, as far as I remember, I've never had a dark mode in Dangerzone.

**Comment by apyrgio** [comment]
I still haven't figured out _why_ we don't detect correctly the system's dark mode. Our code for doing so

https://github.com/freedomofpress/dangerzone/blob/83be5fb151b0c30bad47f173f875b6ce1c20e0bd/dangerzone/gui/__init__.py#L99-L105

is the same as the one in the most recent [Qt blog](https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5) about dark mode:

```
static bool shouldApplyDarkFrame()
{
    // ...
    const QPalette defaultPalette;
    return defaultPalette.color(QPalette::WindowText).lightness()
         > defaultPalette.color(QPalette::Window).lightness();
}
```

In any case, until we have a fix for this, I have successfully experimented with two different ways to force Dangerzone use a dark theme:

## Method 1 - Force dark theme for legacy GTK apps

Install some extra Gnome themes with:

```
sudo dnf install gnome-themes-extra
```

Then, install Gnome Tweaks, open it, go to Appearance -> Styles -> Legacy Applications and choose `Adwaita-dark`.

> [!NOTE]
> This change affects all legacy GTK apps, and not just Dangerzone.

## Method 2 - Force dark theme specifically for Dangerzone

Open a terminal, and start Dangerzone with:

```
GTK_THEME=Adwaita:dark dangerzone
```

---

I don't like much any of these options, so I'll revisit this issue once I have some more time, and solve it properly. In the meantime, if anyone else more experienced in GTK app development has any idea, feel free to share it here.

**Comment by sudwhiwdh** [comment]
> so I'll revisit this issue once I have some more time, and solve it properly.

Thank you!

**Comment by Kol9yN** [comment]
any way to make automated? :)

**Comment by almet** [comment]
Automatically switching was actually implemented in https://github.com/freedomofpress/dangerzone/pull/1389, and will be released with the upcoming 0.11.0 (should happen in the upcoming weeks).

**Comment by sudwhiwdh** [comment]
Has this issue also been addressed in https://github.com/freedomofpress/dangerzone/pull/1389?

**Comment by almet** [comment]
Oh, actually my bad: this has been implemented and works… but only for macOS and Windows systems. On Linux, we still don't detect the dark theme if it changed recently. I'm not sure why that is.

But… the dark theme exists, see:

<img width="622" height="490" alt="Image" src="https://github.com/user-attachments/assets/41e2134b-684c-4653-9550-375b645aa319" />

I'm putting that in our backlog, so we can have a better look at why this is currently not working properly on Gnome.

**Comment by sudwhiwdh** [comment]
This is what Dangerzone looks like in dark mode in GNOME on my computer.

<img width="669" height="812" alt="Image" src="https://github.com/user-attachments/assets/7f6fb3ad-748f-4168-ba79-cb5b84480585" />

And this is what it looks like in light mode. Switching between the two is no problem at all.

<img width="669" height="812" alt="Image" src="https://github.com/user-attachments/assets/5afa0ad0-be41-4cf9-8d7b-984387ba926c" />

**Comment by sudwhiwdh** [comment]
> GTK_THEME=Adwaita:dark dangerzone

That actually works.

<img width="646" height="556" alt="Image" src="https://github.com/user-attachments/assets/b7a75e0b-dbf5-46e4-a345-ba677580bab5" />

`gsettings get org.gnome.desktop.interface color-scheme` returns `'prefer-dark'`. 

Perhaps Dangerzone could check the gsettings upon startup to identify the system theme properly?

**Comment by apyrgio** [comment]
Has anyone managed to make it work with live switching? The `GTK_THEME=Adwaita:dark` approach works on startup, but not if the user switches colors mid-session. It seems to me that Qt does not hook into GTK enough in order to perform such detections, but I'd like to be proven wrong.

If this is correct, then there are two approaches here:
1. Either proceed with a hardcoded dark palette, but it may not look native.
2. Accept that we can't perform live switch yet on Linux, and open a distinct issue about it.

**Comment by sudwhiwdh** [comment]
Is it possible that QT could keep an eye on changes to the relevant gsettings key?

**Comment by apyrgio** [comment]
I don't see a Qt-native way on Linux (on Windows and macOS, we have the necessary code). We can add code that detects it live, but we can't set an envvar in that case, since Qt will already be initialized.
